server:
    port: 8082
#    context-path: /ui
    session:
      cookie:
        name: UISESSION
        
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/oauth/token
      userAuthorizationUri: http://localhost:8081/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/user/me
      

#security.oauth2.resource.service-id={Service ID as at eureka server registered}
#security.oauth2.resource.userInfoUri= http://${security.oauth2.resource.service-id}/user/me
#security.oauth2.resource.loadBalanced=true
#security.oauth2.resource.prefer-token-info=false